# Site settings
author: Christine
title: Christine's Blog
header-img: img/home-bg.png
email: christine.zosche@gmail.com
copyright_name: Christine
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering PT 4/13/20
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  christinezosche

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
